// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type AuthResponse struct {
	AccessToken string `json:"accessToken"`
	User        *User  `json:"user"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Email           string `json:"email"`
	Password        string `json:"password"`
	Username        string `json:"username"`
	ConfirmPassword string `json:"confirmPassword"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	CreateAt string `json:"createAt"`
}
