// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/G0SU19O2/Go-Twitter"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepo creates a new instance of MockUserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepo {
	mock := &MockUserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepo is an autogenerated mock type for the UserRepo type
type MockUserRepo struct {
	mock.Mock
}

type MockUserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepo) EXPECT() *MockUserRepo_Expecter {
	return &MockUserRepo_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) CreateUser(ctx context.Context, user gotwitter.User) (gotwitter.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 gotwitter.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gotwitter.User) (gotwitter.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, gotwitter.User) gotwitter.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(gotwitter.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, gotwitter.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserRepo_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user gotwitter.User
func (_e *MockUserRepo_Expecter) CreateUser(ctx interface{}, user interface{}) *MockUserRepo_CreateUser_Call {
	return &MockUserRepo_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockUserRepo_CreateUser_Call) Run(run func(ctx context.Context, user gotwitter.User)) *MockUserRepo_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gotwitter.User
		if args[1] != nil {
			arg1 = args[1].(gotwitter.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_CreateUser_Call) Return(user1 gotwitter.User, err error) *MockUserRepo_CreateUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserRepo_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user gotwitter.User) (gotwitter.User, error)) *MockUserRepo_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetByEmail(ctx context.Context, email string) (gotwitter.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 gotwitter.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (gotwitter.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) gotwitter.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(gotwitter.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockUserRepo_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepo_Expecter) GetByEmail(ctx interface{}, email interface{}) *MockUserRepo_GetByEmail_Call {
	return &MockUserRepo_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *MockUserRepo_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserRepo_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_GetByEmail_Call) Return(user gotwitter.User, err error) *MockUserRepo_GetByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepo_GetByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (gotwitter.User, error)) *MockUserRepo_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUsername provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetByUsername(ctx context.Context, username string) (gotwitter.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetByUsername")
	}

	var r0 gotwitter.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (gotwitter.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) gotwitter.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Get(0).(gotwitter.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUsername'
type MockUserRepo_GetByUsername_Call struct {
	*mock.Call
}

// GetByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserRepo_Expecter) GetByUsername(ctx interface{}, username interface{}) *MockUserRepo_GetByUsername_Call {
	return &MockUserRepo_GetByUsername_Call{Call: _e.mock.On("GetByUsername", ctx, username)}
}

func (_c *MockUserRepo_GetByUsername_Call) Run(run func(ctx context.Context, username string)) *MockUserRepo_GetByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_GetByUsername_Call) Return(user gotwitter.User, err error) *MockUserRepo_GetByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepo_GetByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (gotwitter.User, error)) *MockUserRepo_GetByUsername_Call {
	_c.Call.Return(run)
	return _c
}
